services:

  cloudbeaver:

    image: dbeaver/cloudbeaver:latest

    container_name: cloudbeaver

    restart: unless-stopped

    ports:
      - "127.0.0.1:8978:8978"

    volumes:
      - /Docker/volumes/cloudbeaver:/opt/cloudbeaver/workspace

    networks:
      - homeserver

networks:

  homeserver:
    external: true