services:
  mysql:
    image: mysql:8.4
    container_name: mysql

    restart: unless-stopped

    env_file:
      - .env

    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

    volumes:
      - /Docker/volumes/mysql:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
      - ./init:/docker-entrypoint-initdb.d:ro

    networks:
      - homeserver

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

    logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

networks:
  homeserver:
    external: true